### ISSUE TITLE
Improve error reporting when a template accesses an invalid profile, secret, or configuration option

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/config_o_mat#2]

**Comment by MrJoy** [comment]
Specifically, if we use a proc on the hash constructor for profiles, we can raise an exception that includes what key was accessed, instead of waiting for a nil reference or some such.

**Comment by AlexSc** [comment]
Starting in 0.4 accessing a key that does not exist using `#[]` on profile or secrets contents will raise a KeyError indicating the missing key and the name of the profile or secret it was accessed on.
